### ISSUE TITLE
Errors Running From Ubuntu

### ISSUE THREAD

**Issue by curtisstpierre** [geerlingguy/packer-ubuntu-1604#11]
While attempting to run this using packer(v0.10.2) I ran into issues when that package attemtps to run
`geerlingguy.nfs`
I then tried to remove that package and just run with
`geerlingguy.packer-debian`
This resulted in new (but similar errors)
```
    virtualbox-iso:
    virtualbox-iso: PLAY ***************************************************************************
    virtualbox-iso:
    virtualbox-iso: TASK [setup] *******************************************************************
    virtualbox-iso: ok: [127.0.0.1]
    virtualbox-iso:
    virtualbox-iso: TASK [geerlingguy.packer-debian : Ensure apt cache is updated.] ****************
    virtualbox-iso: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "apt-get update '&&' apt-get install python-apt -y -q --force-yes", "failed": true, "msg": "debconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nW: --force-yes is deprecated, use one of the options starting with --allow instead.\nE: Sub-process /usr/bin/dpkg returned an error code (1)", "rc": 100, "stderr": "debconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nW: --force-yes is deprecated, use one of the options starting with --allow instead.\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stdout": "Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease\nHit:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease\nHit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease\nGet:4 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.1 kB]\nHit:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease\nGet:6 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [552 B]\nGet:7 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main i386 Packages [552 B]\nGet:8 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main Translation-en [340 B]\nFetched 19.5 kB in 0s (20.2 kB/s)\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nSuggested packages:\n  python-apt-dbg python-apt-doc\nThe following NEW packages will be installed:\n  python-apt\n0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.\n1 not fully installed or removed.\nNeed to get 139 kB of archives.\nAfter this operation, 631 kB of additional disk space will be used.\nGet:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python-apt amd64 1.1.0~beta1build1 [139 kB]\nFetched 139 kB in 0s (162 kB/s)\nSelecting previously unselected package python-apt.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 66690 files and directories currently installed.)\r\nPreparing to unpack .../python-apt_1.1.0~beta1build1_amd64.deb ...\r\nUnpacking python-apt (1.1.0~beta1build1) ...\r\nSetting up sudo (1.8.16-0ubuntu1.2) ...\r\n\r\nConfiguration file '/etc/sudoers'\r\n ==> Modified (by you or by a script) since installation.\r\n ==> Package distributor has shipped an updated version.\r\n   What would you like to do about it ?  Your options are:\r\n    Y or I  : install the package maintainer's version\r\n    N or O  : keep your currently-installed version\r\n      D     : show the differences between the versions\r\n      Z     : start a shell to examine the situation\r\n The default action is to keep your current version.\r\n*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):\r\n end of file on stdin at conffile prompt\r\nSetting up python-apt (1.1.0~beta1build1) ...\r\nErrors were encountered while processing:\r\n sudo\r\n", "stdout_lines": ["Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease", "Hit:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease", "Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease", "Get:4 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.1 kB]", "Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease", "Get:6 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [552 B]", "Get:7 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main i386 Packages [552 B]", "Get:8 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main Translation-en [340 B]", "Fetched 19.5 kB in 0s (20.2 kB/s)", "Reading package lists...", "Reading package lists...", "Building dependency tree...", "Reading state information...", "Suggested packages:", "  python-apt-dbg python-apt-doc", "The following NEW packages will be installed:", "  python-apt", "0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.", "1 not fully installed or removed.", "Need to get 139 kB of archives.", "After this operation, 631 kB of additional disk space will be used.", "Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python-apt amd64 1.1.0~beta1build1 [139 kB]", "Fetched 139 kB in 0s (162 kB/s)", "Selecting previously unselected package python-apt.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 66690 files and directories currently installed.)", "Preparing to unpack .../python-apt_1.1.0~beta1build1_amd64.deb ...", "Unpacking python-apt (1.1.0~beta1build1) ...", "Setting up sudo (1.8.16-0ubuntu1.2) ...", "", "Configuration file '/etc/sudoers'", " ==> Modified (by you or by a script) since installation.", " ==> Package distributor has shipped an updated version.", "   What would you like to do about it ?  Your options are:", "    Y or I  : install the package maintainer's version", "    N or O  : keep your currently-installed version", "      D     : show the differences between the versions", "      Z     : start a shell to examine the situation", " The default action is to keep your current version.", "*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):", " end of file on stdin at conffile prompt", "Setting up python-apt (1.1.0~beta1build1) ...", "Errors were encountered while processing:", " sudo"]}
```

Before I try to continue debugging this, I wanted to check if there is something obvious I'm missing
